// Worker entry (wrangler.jsonc "main"). Wraps the handler OpenNext generates so
// /media/* is served straight from R2 without going through Next.js: cheaper per
// request, and responses keep their Content-Length (Next streams them chunked).
// See https://opennext.js.org/cloudflare/howtos/custom-worker

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore `.open-next/worker.js` is generated by `opennextjs-cloudflare build`
import { default as handler } from "./.open-next/worker.js";
import { serveMedia } from "./src/lib/media/serve";

const MEDIA_PREFIX = "/media/";

export default {
  async fetch(request, env, ctx) {
    const { pathname } = new URL(request.url);
    if (pathname.startsWith(MEDIA_PREFIX)) {
      let key: string;
      try {
        key = decodeURIComponent(pathname.slice(MEDIA_PREFIX.length));
      } catch {
        return new Response("Not found", { status: 404 });
      }
      return serveMedia(request, env.MEDIA, key);
    }
    return handler.fetch(request, env, ctx);
  },
} satisfies ExportedHandler<CloudflareEnv>;
